# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -v ./...

    - name: Heroku cli download
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version

    - name: Heroku login
      run: |
        heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy the container
      run: |
        go build -o go-todo-app .
        ls -l
        heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}
        heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
